service: nestjs-service

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs18.x
  stage: dev
  region: us-east-2
  vpc:
   securityGroupIds:
     - sg-03239aa4358555eaf
   subnetIds:
     - subnet-5387291f
     - subnet-55aaa33d
     - subnet-ed276197
  environment:
    DB_HOST: aws-practitioner-js-6-instance.cb4qkmwcu3qa.us-east-2.rds.amazonaws.com
    DB_PORT: 5432
    DB_NAME: aws_practitioner_js_6
    DB_USER: postgres
    DB_PASSWORD: uGxGSCHwfU75a8HoT1de

functions:
  main:
    handler: dist/main.handler
    events:
      - http:
          method: ANY
          path: /
      - http:
          method: ANY
          path: '{proxy+}'
